import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../css/reset.scss';
import '../css/globals.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import Container from '@/components/common/Container/Container';
import { Providers } from '@/components/common/Providers/Providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Home | Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />

          <main className="main">
            <Container>
              <div className="page-layout">{children}</div>
            </Container>
          </main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
